services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE:-miti}
    volumes:
      - ./mnt/postgres:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    restart: always
    user: root
    ports:
      - 9090:9090
    volumes:
      - type: bind
        read_only: true
        source: ./prometheus.yaml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./mnt/prometheus
        target: /prometheus
  api:
    build: .
    restart: always
    ports:
      - 2727:2727
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_PASSWORD=${DB_PASSWORD}
      - PEPPER=${PEPPER}
    profiles:
      - api
